services:
  ArtCollab:
    image: artcollab
    build:
        context: ../
        dockerfile: Presentation/Dockerfile
    ports:
        - "8080:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
  