services:
  ArtCollab:
    image: artcollab
    build:
      context: ../
      dockerfile: Presentation/Dockerfile
    ports:
      - 5050:5050
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  